apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: builder
  labels:
    skip-release-branch: "true"
    skip-replace-cli: "true"
    skip-replace-builder: "true"
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/znipps/images'
      ref: main
    contextDir: builder
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "tools:centos9"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:builder'
