apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: azure-workload-identity-webhook
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/azure-workload-identity'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:azure-workload-identity-webhook'
