apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-config-api
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/api'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel8
      buildArgs:
        - name: "TAGS"
          value: "scos"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-config-api'
