apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-platform-operators-manager
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/platform-operators'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-platform-operators-manager'
