apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: driver-toolkit
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/driver-toolkit'
      ref: release-4.15
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/driver-toolkit/Dockerfile.centos9
            destinationDir: "./"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
      buildArgs:
      - name: RHEL_VERSION
        value: "9.0"
      - name: KERNEL_VERSION
        value: "5.14.0-467.el9"
      - name: RT_KERNEL_VERSION
        value: "5.14.0-467.el9"
      - name: RHEL_VERSION
        value: "5.14.0-467.el9"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:driver-toolkit'
