apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: installer-terraform-providers
  labels:
    change-build-arg-tags: "true"
    resources-profile: high
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/installer'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/infrastructure-providers/Dockerfile
      buildArgs:
          - name: "TAGS"
            value: "okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'tools:installer-terraform-providers'
