apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kubevirt-csi-driver
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kubevirt-csi-driver'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kubevirt-csi-driver'
