apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ovn-kubernetes
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ovn-kubernetes'
      ref: release-4.15
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/ovn-kubernetes/Dockerfile.mingw
            destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.mingw
      from:
        kind: "ImageStreamTag"
        name: "release:ovn-kubernetes-base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ovn-kubernetes-rhel-9'
