apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
    # The next patch will replace the build-stage images used by the upstream repositories' Dockerfiles with the okd builder one.
    # In particular, each stage extending from an image contained in the `as` array below will start from the ImageStreamTag release:builder
    # In the future, we may change this to be more specific to the builder image features. E.g., we may need one builder image per golang version.
  - patch: |-
      - op: add
        path: "/spec/source/images/-"
        value:
           from:
              kind: "ImageStreamTag"
              name: "release:builder"
           as:
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-nodejs-openshift-4.13'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-nodejs-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-nodejs-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-etcd-golang-1.16'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-etcd-golang-1.19'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-etcd-golang-1.20'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-etcd-golang-1.21'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.9'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.10'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.12'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.13'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.18-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.19-openshift-4.13'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.19-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.19-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.13'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.14'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.15'
             - 'registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16'
             - 'registry.ci.openshift.org/openshift/release:golang-1.17'
             - 'registry.ci.openshift.org/openshift/release:golang-1.18'
             - 'registry.ci.openshift.org/openshift/release:golang-1.19'
             - 'registry.ci.openshift.org/openshift/release:golang-1.20'
             - 'registry.ci.openshift.org/openshift/release:golang-1.21'
    target:
      kind: BuildConfig
      labelSelector: "skip-replace-builder!=true"
  - patch: |-
      - op: add
        path: "/spec/source/images/-"
        value:
          from:
            kind: ImageStreamTag
            name: 'tools:installer-terraform-providers'
          as:
            - 'registry.ci.openshift.org/ocp/4.15:installer-terraform-providers'
    target:
      kind: BuildConfig
      labelSelector: "skip-installer-cli=true"
  - patch: |-
      - op: add
        path: "/spec/source/images/-"
        value:
          from:
            kind: ImageStreamTag
            name: 'release:cli'
          as:
            - 'registry.ci.openshift.org/ocp/4.11:cli'
            - 'registry.ci.openshift.org/ocp/4.12:cli'
            - 'registry.ci.openshift.org/ocp/4.13:cli'
            - 'registry.ci.openshift.org/ocp/4.14:cli'
            - 'registry.ci.openshift.org/ocp/4.15:cli'
    target:
      kind: BuildConfig
      labelSelector: "skip-replace-cli!=true"
  - patch: |-
      - op: add
        path: "/spec/source/images/-"
        value:
          from:
            kind: ImageStreamTag
            name: 'release:artifacts'
          as:
            - 'registry.ci.openshift.org/origin/4.15:artifacts'
    target:
      kind: BuildConfig
      name: fedora-coreos
  # TODO: tune resources req/lim
  - patch: |-
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 4Gi
    target:
      kind: BuildConfig
  - patch: |-
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
    target:
      kind: BuildConfig
      labelSelector: "resources-profile==low"
  # Burstable QoS for high-resources profile
  - patch: |-
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "6"
          requests:
            cpu: "6"
            memory: 8Gi
    target:
      kind: BuildConfig
      labelSelector: "resources-profile==high"
resources:
  - 00-namespace.yaml
  - 01-imagestream.yaml
  - 02-additional-imagestream.yaml
  - 03-forked-dockerfiles.yaml
  - 04-builder.yaml
  - 05-base.yaml
  - 06-cli.yaml
  - 10-agent-installer-node-agent.yaml
  - 10-agent-installer-orchestrator.yaml
  - 10-agent-installer-utils.yaml
  - 10-alibaba-cloud-controller-manager.yaml
  - 10-alibaba-cloud-csi-driver.yaml
  - 10-alibaba-disk-csi-driver-operator.yaml
  - 10-alibaba-machine-controllers.yaml
  - 10-apiserver-network-proxy.yaml
  - 10-aws-cloud-controller-manager.yaml
  - 10-aws-cluster-api-controllers.yaml
  - 10-aws-ebs-csi-driver-operator.yaml
  - 10-aws-ebs-csi-driver.yaml
  - 10-aws-machine-controllers.yaml
  - 10-aws-pod-identity-webhook.yaml
  - 10-azure-cloud-controller-manager.yaml
  - 10-azure-cloud-node-manager.yaml
  - 10-azure-cluster-api-controllers.yaml
  - 10-azure-disk-csi-driver-operator.yaml
  - 10-azure-disk-csi-driver.yaml
  - 10-azure-file-csi-driver-operator.yaml
  - 10-azure-file-csi-driver.yaml
  - 10-azure-machine-controllers.yaml
  - 10-baremetal-installer.yaml
  - 10-baremetal-machine-controllers.yaml
  - 10-baremetal-operator.yaml
  - 10-baremetal-runtimecfg.yaml
  - 10-branding.yaml
  - 10-cli-artifacts.yaml
  - 10-cloud-credential-operator.yaml
  - 10-cloud-network-config-controller.yaml
  - 10-cluster-authentication-operator.yaml
  - 10-cluster-autoscaler-operator.yaml
  - 10-cluster-autoscaler.yaml
  - 10-cluster-baremetal-operator.yaml
  - 10-cluster-bootstrap.yaml
  - 10-cluster-capi-controllers.yaml
  - 10-cluster-capi-operator.yaml
  - 10-cluster-cloud-controller-manager-operator.yaml
  - 10-cluster-config-operator.yaml
  - 10-cluster-control-plane-machine-set-operator.yaml
  - 10-cluster-csi-snapshot-controller-operator.yaml
  - 10-cluster-dns-operator.yaml
  - 10-cluster-etcd-operator.yaml
  - 10-cluster-image-registry-operator.yaml
  - 10-cluster-ingress-operator.yaml
  - 10-cluster-kube-apiserver-operator.yaml
  - 10-cluster-kube-cluster-api-operator.yaml
  - 10-cluster-kube-controller-manager-operator.yaml
  - 10-cluster-kube-scheduler-operator.yaml
  - 10-cluster-kube-storage-version-migrator-operator.yaml
  - 10-cluster-machine-approver.yaml
  - 10-cluster-monitoring-operator.yaml
  - 10-cluster-network-operator.yaml
  - 10-cluster-node-tuning-operator.yaml
  - 10-cluster-openshift-apiserver-operator.yaml
  - 10-cluster-openshift-controller-manager-operator.yaml
  - 10-cluster-policy-controller.yaml
  - 10-cluster-samples-operator.yaml
  - 10-cluster-storage-operator.yaml
  - 10-cluster-update-keys.yaml
  - 10-cluster-version-operator.yaml
  - 10-configmap-reloader.yaml
  - 10-console-operator.yaml
  - 10-console.yaml
  - 10-container-networking-plugins.yaml
  - 10-contour-operator.yaml
  - 10-contour.yaml
  - 10-coredns.yaml
  - 10-csi-driver-manila-operator.yaml
  - 10-csi-driver-manila.yaml
  - 10-csi-driver-nfs.yaml
  - 10-csi-driver-shared-resource-operator.yaml
  - 10-csi-driver-shared-resource-webhook.yaml
  - 10-csi-driver-shared-resource.yaml
  - 10-csi-external-attacher.yaml
  - 10-csi-external-provisioner.yaml
  - 10-csi-external-resizer.yaml
  - 10-csi-external-snapshotter.yaml
  - 10-csi-livenessprobe.yaml
  - 10-csi-node-driver-registrar.yaml
  - 10-csi-snapshot-controller.yaml
  - 10-csi-snapshot-validation-webhook.yaml
  - 10-docker-builder.yaml
  - 10-docker-registry.yaml
  - 10-driver-toolkit.yaml
  - 10-egress-router-cni.yaml
  - 10-etcd.yaml
  - 10-external-dns.yaml
  - 10-gcp-cloud-controller-manager.yaml
  - 10-gcp-cluster-api-controllers.yaml
  - 10-gcp-machine-controllers.yaml
  - 10-gcp-pd-csi-driver-operator.yaml
  - 10-gcp-pd-csi-driver.yaml
  - 10-haproxy-router-base.yaml
  - 10-hyperkube.yaml
  - 10-hypershift.yaml
  - 10-ibm-cloud-controller-manager.yaml
  - 10-ibmcloud-machine-controllers.yaml
  - 10-ibm-vpc-block-csi-driver-operator.yaml
  - 10-ibm-vpc-block-csi-driver.yaml
  - 10-ibm-vpc-node-label-updater.yaml
  - 10-insights-operator.yaml
  - 10-installer-artifacts.yaml
  - 10-installer.yaml
  - 10-installer-terraform-providers.yaml
  - 10-ironic-agent.yaml
  - 10-ironic-hardware-inventory-recorder.yaml
  - 10-ironic-machine-os-downloader.yaml
  - 10-ironic-static-ip-manager.yaml
  - 10-ironic.yaml
  - 10-k8s-prometheus-adapter.yaml
  - 10-keepalived-ipfailover.yaml
  - 10-kube-proxy.yaml
  - 10-kube-rbac-proxy.yaml
  - 10-kube-state-metrics.yaml
  - 10-kube-storage-version-migrator.yaml
  - 10-libvirt-machine-controllers.yaml
  - 10-local-storage-static-provisioner.yaml
  - 10-machine-api-operator.yaml
  - 10-machine-config-operator.yaml
  - 10-machine-image-customization-controller.yaml
  - 10-multus-admission-controller.yaml
  - 10-multus-cni.yaml
  - 10-multus-networkpolicy.yaml
  - 10-multus-route-override-cni.yaml
  - 10-multus-whereabouts-ipam-cni.yaml
  - 10-must-gather.yaml
  - 10-network-interface-bond-cni.yaml
  - 10-network-metrics-daemon.yaml
  - 10-nutanix-cloud-controllerr-manager.yaml
  - 10-nutanix-machine-controllers.yaml
  - 10-oauth-apiserver.yaml
  - 10-oauth-proxy.yaml
  - 10-oauth-server.yaml
  - 10-oc-mirror.yaml
  - 10-openshift-apiserver.yaml
  - 10-openshift-controller-manager.yaml
  - 10-openshift-state-metrics.yaml
  - 10-openstack-cinder-csi-driver-operator.yaml
  - 10-openstack-cinder-csi-driver.yaml
  - 10-openstack-cloud-controller-manager.yaml
  - 10-openstack-machine-api-provider.yaml
  - 10-openstack-machine-controllers.yaml
  - 10-operator-lifecycle-manager.yaml
  - 10-operator-marketplace.yaml
  - 10-operator-registry.yaml
  - 10-ovirt-csi-driver-operator.yaml
  - 10-ovirt-csi-driver.yaml
  - 10-ovirt-installer.yaml
  - 10-ovirt-machine-controllers.yaml
  - 10-pod.yaml
  - 10-powervs-cloud-controller-manager.yaml
  - 10-powervs-machine-controllers.yaml
  - 10-prometheus-alertmanager.yaml
  - 10-prometheus-config-reloader.yaml
  - 10-prometheus-node-exporter.yaml
  - 10-prometheus-operator-admission-webhook.yaml
  - 10-prometheus-operator.yaml
  - 10-prometheus.yaml
  - 10-prom-label-proxy.yaml
  - 10-route-controller-manager.yaml
  - 10-sdn.yaml
  - 10-service-ca-operator.yaml
  - 10-telemeter.yaml
  - 10-thanos.yaml
  - 10-vsphere-cloud-controller-manager.yaml
  - 10-vsphere-cluster-api-controllers.yaml
  - 10-vsphere-csi-driver-operator.yaml
  - 10-vsphere-csi-driver-syncer.yaml
  - 10-vsphere-csi-driver.yaml
  - 10-vsphere-problem-detector.yaml
  - 20-agent-installer-api-server.yaml
  - 20-agent-installer-csr-approver.yaml
  - 20-artifacts.yaml
  - 20-deployer.yaml
  - 20-haproxy-router.yaml
  - 20-machine-os-images.yaml
  - 20-ovn-kubernetes-base.yaml
  - 20-tools.yaml
  - 30-fedora-coreos.yaml
  - 30-network-tools.yaml
  - 30-ovn-kubernetes-microshift.yaml
  - 30-ovn-kubernetes.yaml
  - 30-tests.yaml
  - failing-20-kuryr-cni-base.yaml
  - failing-20-kuryr-cni.yaml
  - failing-20-kuryr-controller.yaml
